services:
  authservice:
    image: authservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATIONMINUTES=${JWT_EXPIRATIONMINUTES}
